pipeline:
  name: Create Template
  identifier: Create_Template
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Template
        identifier: deploy_template
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: <+env.variables.*>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: TerraformApply
                  name: apply
                  identifier: apply
                  spec:
                    provisionerIdentifier: apply
                    configuration:
                      type: Inline
                      skipStateStorage: true
                      spec:
                        configFiles:
                          store:
                            spec:
                              connectorRef: account.Aditya_Github_Account_Connector
                              gitFetchType: Branch
                              branch: main
                              folderPath: <+input>
                              repoName: Template-Library
                            type: Github
                        environmentVariables:
                          - name: HARNESS_ACCOUNT_ID
                            value: <+account.identifier>
                            type: String
                          - name: HARNESS_PLATFORM_API_KEY
                            value: <+secrets.getValue("account.harness_platform_api_key")>
                            type: String
                  timeout: 10m
                  when:
                    stageStatus: Success
                    condition: "false"
          environment:
            environmentRef: account.Prod_Env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harness_K8sInfra
                inputs:
                  identifier: harness_K8sInfra
                  type: KubernetesDirect
                  spec:
                    provisioner: <+input>
        tags: {}
